Update flake.nix and flake.lock
- Add instructions on how to update in the future
- Add iterm2 and remove alacritty
- Remove UTM from installation and dock
- Alacritty error

```
error: linking with `/nix/store/4cxvdil6ap4xsgbrpn4jmhj5gp60l1rw-clang-wrapper-16.0.6/bin/cc` failed: exit status: 1
  |
  = note: env -u IPHONEOS_DEPLOYMENT_TARGET -u TVOS_DEPLOYMENT_TARGET LC_ALL="C" PATH="/nix/store/yldcizs9i56576njlniavnr7sddafsgh-rustc-1.74.0/lib/rust>
  = note: Undefined symbols for architecture x86_64:
            "_NSPasteboardTypeFileURL", referenced from:
                objc::rc::autorelease::autoreleasepool::ha8ebbee24d12f407 in alacritty-b347e2f7b8586748.copypasta-391a6e9e8e7011eb.copypasta.13839ede928>
          ld: symbol(s) not found for architecture x86_64
          clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```